"""non volatile cache for course and topicContent

Revision ID: 56358e8f4e57
Revises: a8ea951ff0cf
Create Date: 2026-01-19 23:46:50.445214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56358e8f4e57'
down_revision = 'a8ea951ff0cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic_contents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.String(length=100), nullable=False),
    sa.Column('module_number', sa.Integer(), nullable=True),
    sa.Column('chapter_number', sa.Integer(), nullable=True),
    sa.Column('topic_number', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('key_points', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('videos', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('generated_at', sa.String(length=100), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('topic_contents', schema=None) as batch_op:
        batch_op.create_index('idx_content_hash_status', ['content_hash', 'status'], unique=False)
        batch_op.create_index('idx_course_status', ['course_id', 'status'], unique=False)
        batch_op.create_index('idx_course_topic', ['course_id', 'topic_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_topic_contents_content_hash'), ['content_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic_contents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topic_contents_content_hash'))
        batch_op.drop_index('idx_course_topic')
        batch_op.drop_index('idx_course_status')
        batch_op.drop_index('idx_content_hash_status')

    op.drop_table('topic_contents')
    # ### end Alembic commands ###
