"""Initial migration - users and courses tables

Revision ID: a3dcc788890a
Revises: 
Create Date: 2026-01-23 01:39:59.486945

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a3dcc788890a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('generating', 'completed', 'failed', name='course_status'), nullable=False),
    sa.Column('course_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_modules', sa.Integer(), nullable=True),
    sa.Column('total_chapters', sa.Integer(), nullable=True),
    sa.Column('total_topics', sa.Integer(), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index('idx_course_json_gin', ['course_json'], unique=False, postgresql_using='gin')
        batch_op.create_index('idx_user_status', ['user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_user_id'), ['user_id'], unique=False)

    op.create_table('course_checkpoints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('stage1_outline', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stage2_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stage3_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stage4_resources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_stage', sa.Enum('stage1', 'stage2', 'stage3', 'stage4', 'completed', name='pipeline_stage'), nullable=True),
    sa.Column('completed_stages', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('llm_prompts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('llm_responses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('stage_tokens', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_successful_topic', sa.String(length=100), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('error_log', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course_checkpoints', schema=None) as batch_op:
        batch_op.create_index('idx_current_stage', ['current_stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_checkpoints_course_id'), ['course_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_checkpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_checkpoints_course_id'))
        batch_op.drop_index('idx_current_stage')

    op.drop_table('course_checkpoints')
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_user_id'))
        batch_op.drop_index(batch_op.f('ix_courses_status'))
        batch_op.drop_index('idx_user_status')
        batch_op.drop_index('idx_course_json_gin', postgresql_using='gin')

    op.drop_table('courses')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
